config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root 'teddies#index'
resources :teddies, only: [:index, :show]
resources :orders, only: [:show, :create] do
  resources :payments, only: :new

end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :teddy
  monetize :amount_cents
end

app/models/teddy.rb
class Teddy < ApplicationRecord
  belongs_to :category
  monetize :price_cents
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    # Assuming you get teddy_id from params or another source
    teddy = Teddy.find(params[:teddy_id])

    # Create a Price object in Stripe
    price = Stripe::Price.create({
      unit_amount: teddy.price_cents,
      currency: 'eur',
      product_data: {
        name: teddy.sku,
        images: [teddy.photo_url],
      },
    })

    # Create the order and reference the created Price object in line_items
    order = Order.create!(teddy: teddy, teddy_sku: teddy.sku, amount: teddy.price, state: 'pending', user: current_user)

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        price: price.id,
        quantity: 1,
      }],
      success_url: order_url(order),
      cancel_url: order_url(order)
    )

    order.update(checkout_session_id: session.id)
    redirect_to new_order_payment_path(order)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end
end

app/controllers/teddies_controller.rb
class TeddiesController < ApplicationController
  skip_before_action :authenticate_user!

def index
  @teddies = Teddy.all
end

def show
  @teddy = Teddy.find(params[:id])
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webpack</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/payments/new.html.erb
<!-- app/views/payments/new.html.erb -->
<div class="container">
  <div class="row py-4">
    <div class="col-md-3"><%= image_tag @order.teddy.photo_url, width: '100%' %></div>
    <div class="col">
      <h1>Checkout summary</h1>
      <p>Purchase of <strong><%= @order.teddy.name %></strong> for <strong><%= humanized_money_with_symbol @order.amount %></strong></p>
      <button id="pay" class="btn btn-primary">Pay</button>

      <script src="https://js.stripe.com/v3/"></script>
      <script>
        const paymentButton = document.getElementById('pay');
        paymentButton.addEventListener('click', () => {
          const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
          stripe.redirectToCheckout({
            sessionId: '<%= @order.checkout_session_id %>'
          });
        });
      </script>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/teddies/index.html.erb
<!-- app/views/teddies/index.html.erb -->
<div class="container">
  <h1>Teddies</h1>
  <div class="row">
    <% @teddies.each do |teddy| %>
      <div class="col-6 col-md-4">
        <div class="card">
          <%= image_tag teddy.photo_url , class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= teddy.name %></h5>
            <p class="card-text"><%= teddy.category.name %></p>
            <p>Amount: <%= humanized_money_with_symbol(teddy.price) %></p>
            <%= link_to "More details", teddy_path(teddy), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/teddies/show.html.erb
<!-- app/views/teddies/show.html.erb -->
<div class="container py-3">
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <%= image_tag(@teddy.photo_url, width: '100%') %>
    </div>
    <div class="col-sm-12 col-md-6">
      <h1><%= @teddy.name %></h1>
      <p>Some awesome description of our amazing teddy.</p>
      <p>Amount: <%= humanized_money_with_symbol(@teddy.price) %></p>
      <%= form_with url: orders_path do %>
        <%= hidden_field_tag 'teddy_id', @teddy.id %>
        <%= submit_tag 'Purchase', class: 'btn btn-primary' %>
      <% end %>

    </div>

  </div>
</div>